service: default
instance_class: F1
runtime: python27
api_version: 1
threadsafe: true

builtins:
  - appstats: on
  - deferred: on
  - remote_api: on

inbound_services:
  - warmup

libraries:
  - name: flask
    version: latest
  - name: jinja2
    version: latest
  - name: lxml
    version: latest
  - name: ssl
    version: latest

error_handlers:
  - file: templates/error_static.html

handlers:
  - url: /favicon.ico
    static_files: static/img/favicon.ico
    upload: static/img/favicon.ico

  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/robots.txt

  - url: /p/(.*\.ttf)
    static_files: static/\1
    upload: static/(.*\.ttf)
    mime_type: font/ttf
    expiration: '365d'

  - url: /p/(.*\.woff2)
    static_files: static/\1
    upload: static/(.*\.woff2)
    mime_type: font/woff2
    expiration: '365d'

  - url: /p/
    static_dir: static/
    expiration: '365d'

  - url: /.*
    script: main.app
    secure: always
    redirect_http_response_code: 301

